import pandas as pd

def create_parameters_dataframe(
    current_age, partner_current_age, life_expectancy, retirement_age,
    partner_retirement_age, initial_savings, stock_percentage, bond_percentage,
    annual_earnings, self_yearly_increase, tax_rate, partner_earnings, partner_yearly_increase, 
    annual_pension, partner_pension, self_pension_yearly_increase, partner_pension_yearly_increase,
    rental_start, rental_end, rental_amt, rental_yearly_increase,     
    # New parameters from Tab 2 (Savings)
    self_401k_balance, partner_401k_balance,
    roth_ira_balance, cash_savings_balance, brokerage_balance,
    # New parameters from Tab 4 (Taxes)
    self_401k_contribution, partner_401k_contribution, employer_self_401k_contribution,
    employer_partner_401k_contribution, maximize_self_contribution, maximize_partner_contribution,
    #
    annual_expense, mortgage_payment, inflation_mean,
    annual_expense_decrease, mortgage_years_remaining, inflation_std,
    annual_social_security, withdrawal_start_age, cola_rate,
    partner_social_security, partner_withdrawal_start_age,
    self_healthcare_cost, self_healthcare_start_age,
    partner_healthcare_cost, partner_healthcare_start_age,
    stock_return_mean, bond_return_mean, simulations,
    stock_return_std, bond_return_std, years_until_downsize,
    residual_amount, adjust_expense_year_1, adjust_expense_amount_1,
    adjust_expense_year_2, adjust_expense_amount_2,
    adjust_expense_year_3, adjust_expense_amount_3,
    one_time_year_1, one_time_amount_1,
    one_time_year_2, one_time_amount_2,
    one_time_year_3, one_time_amount_3,
    windfall_year_1, windfall_amount_1,
    windfall_year_2, windfall_amount_2,
    windfall_year_3, windfall_amount_3,
    simulation_type
):
    # Create a DataFrame with all input fields
    params_df = pd.DataFrame({
        "current_age": [current_age],
        "partner_current_age": [partner_current_age],
        "life_expectancy": [life_expectancy],
        "retirement_age": [retirement_age],
        "partner_retirement_age": [partner_retirement_age],
        "initial_savings": [initial_savings],
        "stock_percentage": [stock_percentage],
        "bond_percentage": [bond_percentage],
        "annual_earnings": [annual_earnings],
        "self_yearly_increase": [self_yearly_increase],
        "tax_rate": [tax_rate],
        "partner_earnings": [partner_earnings],
        "partner_yearly_increase": [partner_yearly_increase],
        "annual_pension": [annual_pension],
        "partner_pension": [partner_pension],
        "self_pension_yearly_increase": [self_pension_yearly_increase],
        "partner_pension_yearly_increase": [partner_pension_yearly_increase],
        "rental_start": [rental_start],
        "rental_end": [rental_end],
        "rental_amt": [rental_amt],
        "rental_yearly_increase": [rental_yearly_increase],
        # New parameters from Tab 2 (Savings)
        "self_401k_balance": [self_401k_balance],
        "partner_401k_balance": [partner_401k_balance],
        "roth_ira_balance": [roth_ira_balance],
        "cash_savings_balance": [cash_savings_balance],
        "brokerage_balance": [brokerage_balance],
        # New parameters from Tab 4 (Taxes)
        "self_401k_contribution": [self_401k_contribution],
        "partner_401k_contribution": [partner_401k_contribution],
        "employer_self_401k_contribution": [employer_self_401k_contribution],
        "employer_partner_401k_contribution": [employer_partner_401k_contribution],
        "maximize_self_contribution": [maximize_self_contribution],
        "maximize_partner_contribution": [maximize_partner_contribution],
        #
        "annual_expense": [annual_expense],
        "mortgage_payment": [mortgage_payment],
        "inflation_mean": [inflation_mean],
        "annual_expense_decrease": [annual_expense_decrease],
        "mortgage_years_remaining": [mortgage_years_remaining],
        "inflation_std": [inflation_std],
        "annual_social_security": [annual_social_security],
        "withdrawal_start_age": [withdrawal_start_age],
        "cola_rate": [cola_rate],
        "partner_social_security": [partner_social_security],
        "partner_withdrawal_start_age": [partner_withdrawal_start_age],
        "self_healthcare_cost": [self_healthcare_cost],
        "self_healthcare_start_age": [self_healthcare_start_age],
        "partner_healthcare_cost": [partner_healthcare_cost],
        "partner_healthcare_start_age": [partner_healthcare_start_age],
        "stock_return_mean": [stock_return_mean],
        "bond_return_mean": [bond_return_mean],
        "simulations": [simulations],
        "stock_return_std": [stock_return_std],
        "bond_return_std": [bond_return_std],
        "years_until_downsize": [years_until_downsize],
        "residual_amount": [residual_amount],
        "adjust_expense_year_1": [adjust_expense_year_1],
        "adjust_expense_amount_1": [adjust_expense_amount_1],
        "adjust_expense_year_2": [adjust_expense_year_2],
        "adjust_expense_amount_2": [adjust_expense_amount_2],
        "adjust_expense_year_3": [adjust_expense_year_3],
        "adjust_expense_amount_3": [adjust_expense_amount_3],
        "one_time_year_1": [one_time_year_1],
        "one_time_amount_1": [one_time_amount_1],
        "one_time_year_2": [one_time_year_2],
        "one_time_amount_2": [one_time_amount_2],
        "one_time_year_3": [one_time_year_3],
        "one_time_amount_3": [one_time_amount_3],
        "windfall_year_1": [windfall_year_1],
        "windfall_amount_1": [windfall_amount_1],
        "windfall_year_2": [windfall_year_2],
        "windfall_amount_2": [windfall_amount_2],
        "windfall_year_3": [windfall_year_3],
        "windfall_amount_3": [windfall_amount_3],
        "simulation_type" : [simulation_type]
    })
    
    return params_df